---
- name: Delete onlyoffice dir for sec_installation
  shell: rm -rf /data/wwwroot/onlyoffice

- name: Clone onlyoffice in Websoft9 
  git:
    repo: "{{onlyoffice_url}}"
    dest: "/data/wwwroot/onlyoffice"

- name: Create dir for onlyoffice
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  loop: 
    - /data/wwwroot/onlyoffice/volumes
    - /data/db/mysql/
    
- name: Rename compose, env filename and Run the docker-compose
  shell: |
    mv docker-compose-production.yml docker-compose.yml
    mv .env_all .env
    docker-compose up -d
    sleep 30
  args:
    chdir: /data/wwwroot/onlyoffice

- name: Create a Apache Log symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: /data/wwwroot/onlyoffice/volumes/document_log/,dest:  /data/logs/documentserver}
  - {src: /data/wwwroot/onlyoffice/volumes/community_log/,dest: /data/logs/communityserver}
  - {src: /data/wwwroot/onlyoffice/volumes/mysql_data/,dest: /data/db/mysql/data}
  - {src: /data/wwwroot/onlyoffice/volumes/config/,dest: /data/db/mysql/config}

- name: Check onlyoffice Version
  shell: sudo echo $(docker inspect onlyoffice/communityserver  | grep onlyoffice.community.version |sed -n 1p |sed 's/"/ /g')|awk '{print $1 $2 $3} | tee -a /data/logs/install_version.txt

- name: Check onlyofficedocumentserver Version
  shell: sudo echo "onlyofficedocumentserver version:" $(docker images |grep onlyoffice/documentserver |awk '{print $2}') | tee -a /data/logs/install_version.txt

- name: Check onlyoffice Service
  shell: echo "onlyoffice" `docker inspect onlyoffice |grep -i status`
  register: check_onlyoffice_service
  notify: check_onlyoffice_service

- name: Check onlyofficedocumentserver Service
  shell: echo "onlyoffice-docs" `docker inspect onlyoffice-docs |grep -i status`
  register: check_onlyofficedocs_service
  notify: check_onlyofficedocs_service
